fix: Add missing streamlit methods to test mock
- Added st.info, st.success, st.error, st.warning methods to test mock
- This fixes the AttributeError in test_boot_restore_calls_ghrestore
- Test was failing because debug messages use st.info() which wasn't mocked

Fixes test failure: 'types.SimpleNamespace' object has no attribute 'info'